### ISSUE TITLE
wins10colours() destructor

### ISSUE THREAD

**Issue by Shoelace** [stefankueng/sktoolslib#1]
I was just rummaging through the sourcecode and noticed this potential error..
sorry if this is wrong but i figured its best to let you know

in `Win10Colors::~Win10Colors()`
the code reads

```
Win10Colors::~Win10Colors()
{
    if (winrt)
        FreeLibrary(winrt);
    if (winrt_string)
        FreeLibrary(winrt);
}
```

should the second `FreeLibrary` call be using the winrt_string variable as its argument?

**Comment by stefankueng** [comment]
Yes, of course.
Thanks for spotting that.
