### ISSUE TITLE
feature request: visual mouse clicks

### ISSUE THREAD

**Issue by piterq** [stefankueng/sktoolslib#3]
Display animated circles around mouse pointer on mouse click events. Each mouse button should generate animation with its own color.

**Comment by stefankueng** [comment]
I think this issue doesn't belong to this project. sktoolslib is only a library which is used in my other projects.
Maybe you wanted to open this issue for another project?

**Comment by piterq** [comment]
Sorry, I've opened this issue in wrong project.
